// Code generated by tygo. DO NOT EDIT.
import type { CardTitle, TitleCandidate } from "../models/card";

//////////
// source: types.go
/*
Package api defines the JSON shapes of the custom API routes.
tygo turns this package into frontend/src/lib/api/generated.ts
(see tygo.yaml), so the frontend types cannot drift from these.
*/

/**
 * CreateCardRequest is the body of POST /api/admin/cards.
 */
export interface CreateCardRequest {
  pot: string;
  titleCandidate: TitleCandidate;
}
/**
 * UpdateCardTitleRequest is the body of POST /api/admin/cards/{id}/title.
 */
export interface UpdateCardTitleRequest {
  titleCandidate: TitleCandidate;
}
/**
 * LinkedCard is one card entry in the links1hop / links2hop responses.
 */
export interface LinkedCard {
  title: CardTitle;
  titleLc: string;
  /**
   * Raw JSON as stored in the "description" field (a list of lines).
   */
  description: string[] | null;
  image: string;
  pin: boolean;
  target_titleLc: string[];
}
/**
 * Link2HopCard is one row of the links2hop response: a card that links to
 * the shared target Via*, which the open card links to as well. A card
 * sharing several targets appears once per target. Rows of the same target
 * are adjacent, in the order the targets appear in the open card.
 */
export interface Link2HopCard {
  LinkedCard: LinkedCard;
  via_title: string;
  via_titleLc: string;
}
