// Code generated by tygo. DO NOT EDIT.
import type { CardTitle, TitleCandidate } from "../models/card";

//////////
// source: types.go
/*
Package api defines the JSON shapes of the custom API routes.
tygo turns this package into frontend/src/lib/api/generated.ts
(see tygo.yaml), so the frontend types cannot drift from these.
*/

/**
 * CreateCardRequest is the body of POST /api/admin/cards.
 */
export interface CreateCardRequest {
  pot: string;
  titleCandidate: TitleCandidate;
}
/**
 * LinkedCard is one card entry in the links1hop / links2hop responses.
 */
export interface LinkedCard {
  id: string;
  title: CardTitle;
  titleLc: string;
  /**
   * Raw JSON as stored in the "description" field (a list of lines).
   */
  description: string[] | null;
  image: string;
  pin: boolean;
  target_titleLc: string[];
}
/**
 * Link2HopCard is one row of the links2hop response: a card that links to
 * the shared target (ViaTitle), which the open card links to as well. A card
 * sharing several targets appears only once, under the first of them in the
 * open card. Rows of the same target are adjacent, in the order the targets
 * appear in the open card.
 */
export interface Link2HopCard extends LinkedCard {
  via_title: string;
  via_titleLc: string;
}
/**
 * RenameLinksRequest is the body of POST /api/admin/cards/{id}/rename-links.
 * The new title is not sent: the card's current title is used.
 */
export interface RenameLinksRequest {
  oldTitle: string;
}
/**
 * RenameLinksResponse reports how many cards had their links rewritten.
 */
export interface RenameLinksResponse {
  updated: number /* int */;
}
/**
 * SeenRequest is the body of POST /api/admin/cards/{id}/seen. Seen maps a Yjs
 * client id to the next clock of that client the user has seen (a state
 * vector as JSON).
 */
export interface SeenRequest {
  seen: { [key: string]: number /* uint64 */};
}
/**
 * SeenResponse is the body of GET /api/admin/cards/{id}/seen. It is empty
 * when the user has not seen the card yet.
 */
export interface SeenResponse {
  seen: { [key: string]: number /* uint64 */};
}
